version: '3'
services:
  # Nest.js application
  nest-app:
    build: .
    ports:
      - "8080:8080" # Map the host port to the container port
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo
    ports:
      - "27017:27017" # Map the host port to the container port
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password # Set your desired password here
    volumes:
      - mongo-data:/data/hotels # Persist data by using volumes

volumes:
  mongo-data:
